# Generated by Django 3.2.9 on 2021-11-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Автор курса')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('status', models.BooleanField(default=True, verbose_name='Активный')),
                ('image', models.ImageField(blank=True, upload_to='uploads/author', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Активный')),
                ('image', models.ImageField(blank=True, upload_to='uploads/category', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Категория курсов',
                'verbose_name_plural': 'Категории курсов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('image', models.ImageField(blank=True, upload_to='uploads/course', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Видео курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('advantages', models.JSONField(blank=True, verbose_name='Преимущества курса')),
                ('status', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
                ('authors', models.ManyToManyField(blank=True, related_name='authors', to='course.Author', verbose_name='Авторы курса')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='course.category')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Язык курса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки курсов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование тэга')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('status', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги курсов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('A', models.CharField(max_length=255, verbose_name='Вопрос А')),
                ('B', models.CharField(max_length=255, verbose_name='Вопрос B')),
                ('C', models.CharField(max_length=255, verbose_name='Вопрос C')),
                ('D', models.CharField(max_length=255, verbose_name='Вопрос D')),
                ('E', models.CharField(max_length=255, verbose_name='Вопрос E')),
                ('answer', models.CharField(choices=[('A', 'Ответ А'), ('B', 'Ответ B'), ('C', 'Ответ C'), ('D', 'Ответ D'), ('E', 'Ответ E')], default='A', max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование курса')),
                ('image', models.ImageField(blank=True, upload_to='uploads/lesson/image', verbose_name='Изображение')),
                ('file', models.ImageField(blank=True, upload_to='uploads/lesson/file', verbose_name='Дополнительный файл')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Видеоурок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Видеоурок',
                'verbose_name_plural': 'Видеоуроки',
                'ordering': ['-order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='language', to='course.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='course.Tag', verbose_name='Тэги'),
        ),
    ]
