# Generated by Django 3.2.9 on 2021-11-29 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_quiz_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Подтекст курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='course.category', verbose_name='Категория курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='language', to='course.language', verbose_name='Язык курса'),
        ),
    ]
