# Generated by Django 3.2.9 on 2021-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211129_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='advantages',
            field=models.TextField(blank=True, verbose_name='Преимущества курса'),
        ),
    ]
