# Generated by Django 3.2.9 on 2021-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_A',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_B',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_C',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_D',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_E',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование теста'),
        ),
    ]
