# Generated by Django 3.2.9 on 2021-11-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20211129_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'Ответ А'), ('B', 'Ответ B'), ('C', 'Ответ C'), ('D', 'Ответ D'), ('E', 'Ответ E')], default='A', max_length=255, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_A',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Файл к Вопрос А'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_B',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Файл к Вопрос B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_C',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Файл к Вопрос C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_D',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Файл к Вопрос D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_E',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Файл к Вопрос E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Файл к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.quiz', verbose_name='Экзамен'),
        ),
    ]
