# Generated by Django 3.2.9 on 2021-12-01 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211129_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Видеоурок', 'verbose_name_plural': 'Видеоуроки'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='subtitle',
            field=models.CharField(default=datetime.datetime(2021, 12, 1, 7, 59, 9, 838948, tzinfo=utc), max_length=255, verbose_name='Подтекст курса'),
            preserve_default=False,
        ),
    ]
