# Generated by Django 3.2.9 on 2021-12-01 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20211201_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Соц сеть Facebook'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Соц сеть Инстаграм'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='author',
            name='postbox',
            field=models.URLField(blank=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Профессианальная компетенция'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Соц сеть twitter'),
        ),
        migrations.AddField(
            model_name='author',
            name='vk',
            field=models.URLField(blank=True, verbose_name='Соц сеть VK'),
        ),
    ]
