# Generated by Django 3.2.9 on 2021-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20211201_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course.Author', verbose_name='Авторы курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course.Tag', verbose_name='Тэги'),
        ),
    ]
