# Generated by Django 3.2.9 on 2021-12-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lessons',
            field=models.ManyToManyField(related_name='quizzes', to='course.Lesson'),
        ),
    ]
